### ISSUE TITLE
Installation fails when HELM_HOME in not set

### ISSUE THREAD

**Issue by vdboor** [fabmation-gmbh/helm-whatup#10]
I'm trying to install the plugin, but this fails:

```
❯ helm plugin install https://github.com/fabmation-gmbh/helm-whatup
Downloading https://github.com/fabmation-gmbh/helm-whatup/releases/download/v0.2.0/helm-whatup-0.2.0-darwin-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   628    0   628    0     0   2116      0 --:--:-- --:--:-- --:--:--  2114
100 7915k  100 7915k    0     0  1887k      0  0:00:04  0:00:04 --:--:-- 2731k
Preparing to install into /plugins/helm-whatup
cp: /plugins/helm-whatup: No such file or directory
cp: /tmp/helm-whatup/bin: unable to copy extended attributes to /plugins/helm-whatup: No such file or directory
cp: /plugins/helm-whatup/helm-whatup: No such file or directory
Failed to install helm-whatup
	For support, go to https://github.com/fabmation-gmbh/helm-whatup.
Error: plugin install hook for "whatup" exited with error
```

I'm using helm 3, but this issue was also visible on helm 2.

The following fixes some parts of installation on helm 3: `export HELM_HOME=$HOME/Library/helm`

However, actual support on helm 3 appears to be broken.

**Comment by l0nax** [comment]
Since the "Plugin" must be installed in the `$HELM_HOME/...` Directory, I think the only way to also install it is to use the default Paths `$HOME/.helm/...`

**Comment by l0nax** [comment]
@vdboor Can you please send me more specific information about the Helm3 problem?

**Comment by l0nax** [comment]
I fixed the Installation Script but it seems like that the API has changed, so it needs some more work.
Please be patient.

**Comment by vdboor** [comment]
> Can you please send me more specific information about the Helm3 problem?

I only get:

```
helm whatup
Error: plugin "whatup" exited with error
```

One of the problems is, that helm doesn't use tiller anymore - while whatup tries to connect with that.

The paths also changed; where helm2 used `~/.helm/`, this is now `~/Library/helm` on OSx and `~/Library/Caches/helm` for temp files. The `helm env` command shows the actual paths.

However, perhaps it would even be more useful to integrate this plugin into the core of helm instead? (e.g. a `helm outdated` command?)

**Comment by l0nax** [comment]
Yes, that is a good idea, I will create an Issue on the helm repository and I will work on a PR to integrate this Feature.

But since the Code should be the same, for the time being, I will update this Plugin to support Helm 3 until the PR gets accepted.

Thanks @vdboor

**Comment by l0nax** [comment]
@vdboor The implementation is finished and the PR is created (helm/helm#7021)
If you have any Improvements please write them below the PR.

Thanks!
