### ISSUE TITLE
Show example output for USAGE in README

### ISSUE THREAD

**Issue by HungUnicorn** [fabmation-gmbh/helm-whatup#20]
README shows the usage
https://github.com/fabmation-gmbh/helm-whatup/blob/master/README.md#usage

It would be better to provide some/one example output after running `helm whatup`

**Comment by l0nax** [comment]
Will be an asciinema Record also be okay? @HungUnicorn
Because it shows more than "only" an Output.

**Comment by l0nax** [comment]
Done with 5ac0113df04fdc380b563ac53e7b1177e269056e
