### ISSUE TITLE
Custom chart fail the whole lookup

### ISSUE THREAD

**Issue by orefalo** [fabmation-gmbh/helm-whatup#25]
Love this plugin, it's handy

I have a namespace with a mix of OOB and custom charts, the whatup process fails with:

**ERROR: Could not initialize search index: Could not find any Repo which contains vectorError: plugin "whatup" exited with error**

"vector" is a custom chart I built.

Expected behavior: skill the problematic chart and process the next.

**Comment by mfamador** [comment]
If you use it with `--ignore-repo` it will get you through it.

```
❯ helm whatup --all-namespaces --ignore-repo
WARNING: No Repo was found which containing the Chart 'api' (skipping)
NAME               	NAMESPACE  	INSTALLED VERSION	LATEST VERSION	CHART
prometheus-operator	monitoring 	8.13.7           	8.13.8        	prometheus-operator
```
Note that it only shows the outdated charts, which is not the same behaviour as the original plugin.

**Comment by l0nax** [comment]
I'm sorry for my late answer.

As @mfamador you can use the `--ignore-repo` flag.

Did I understand it correctly that the `vector` helm chart is one which you've created locally and are installing it with `helm install ./vector […]`?

Would it help you if those flags would be configurable via environment variables, so you do not have to pass them every time manually?

**Comment by l0nax** [comment]
You can now set the `HELM_WHATUP_IGNORE_REPO=true` environment variable so you do not have to add the `--ignore-repo` flag every time you are using the plugin.

**Comment by l0nax** [comment]
With version _v0.4.0_ this should be fixed.

Feel free to re-open or create a new Issue if your problem hasn't been resolved.

**Comment by orefalo** [comment]
Sorry for late reply, tks a bunch.
I would argue: the flag should be ON by default

**Comment by l0nax** [comment]
Okay, I will enable it and release _v0.4.1_.

**Comment by l0nax** [comment]
Version [_0.4.1_](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.4.1) has been released so the `--ignore-repo` flag is enabled by default.

Thanks for opening this issue and for your patience @orefalo :+1:

**Comment by orefalo** [comment]
cool , tks!
