### ISSUE TITLE
Dockerfile install

### ISSUE THREAD

**Issue by KevinKeo** [fabmation-gmbh/helm-whatup#26]
Hi,

I am running helm inside a container.
I do succeed in installing :
 helm plugin install https://github.com/chartmuseum/helm-push

But for the plugin whatup, I got that strange error and I had no clue..
```
Downloading https://github.com/fabmation-gmbh/helm-whatup/releases/download/v0.3.2/helm-whatup-0.3.2-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   649  100   649    0     0   1563      0 --:--:-- --:--:-- --:--:--  1563
100 17.9M  100 17.9M    0     0   544k      0  0:00:33  0:00:33 --:--:--  623k
Preparing to install into /root/.local/share/helm/plugins/helm-whatup
helm-whatup installed into /root/.local/share/helm/plugins/helm-whatup/helm-whatup
/root/.local/share/helm/plugins/helm-whatup/install-binary.sh: line 104: /root/.local/share/helm/plugins/helm-whatup/bin/helm-whatup: No such file or directory
Installed plugin: whatup
```

I am just doing a RUN helm plugin install https://github.com/fabmation-gmbh/helm-whatup

The plugin are indeed installed in /root/.local/share/helm/plugins/helm-whatup/bin/  but when using the command, I get : 
`Error: fork/exec /root/.local/share/helm/plugins/helm-whatup/bin/helm-whatup: no such file or directory`

Thanks

**Comment by l0nax** [comment]
I'm sorry for the late answer.

Would it be possible if you share your `Dockerfile`?

**Comment by l0nax** [comment]
The `no such file or directory` does mean that some libraries (probably glibc) aren't found/ installed on your system.

For the future releases I will link the binaries _statically_, this should fix your error.

**Comment by l0nax** [comment]
With version v0.4.0 this should be fixed.

Feel free to re-open or create a new Issue if your problem hasn't been resolved.
