### ISSUE TITLE
Installation fails unless bash is installed

### ISSUE THREAD

**Issue by digitalronin** [fabmation-gmbh/helm-whatup#34]
Hi there

Installing helm and this plugin into a docker image, I was getting this error when installing the plugin:

```
 > [6/6] RUN helm plugin install https://github.com/fabmation-gmbh/helm-whatup:
#9 5.021 sh: /root/.local/share/helm/plugins/helm-whatup/install-binary.sh: not found
#9 5.022 Error: plugin install hook for "whatup" exited with error
```
The "not found" refers to `/bin/bash` which I didn't have installed.

If the `install-binary.sh` script could use `/bin/sh` instead of bash, it would avoid the extra step of installing bash in docker images. I know it's not particularly difficult, but it confused me for a little while, so maybe other folks are experiencing the same problem.

**Comment by l0nax** [comment]
Would it be possible for you to _temporarily_ install `bash`?

**Comment by digitalronin** [comment]
Sure, but my point is that it's unnecessary.
