### ISSUE TITLE
Default output shows deprecated charts

### ISSUE THREAD

**Issue by stevehipwell** [fabmation-gmbh/helm-whatup#35]
The current output shows charts that have been deprecated and there isn't a flag to hide them, this wasn't such a big deal before stable was deprecated but now it makes the output very noisy and requires more documentation around how to interpret the results.

My personal preference would be for a flag to show deprecated charts with the default behaviour being to not show them.

FYI I really appreciate that you've kept this plugin working as I feel an outdated command should be part of core Helm (it's a fundamental package manager feature).

**Comment by l0nax** [comment]
Implemented in commit a48a5f9be32289620bcdfa278c576a176df7b224

**Comment by stevehipwell** [comment]
Thanks @l0nax I think I mentioned this in another issue, please ignore it there.
