### ISSUE TITLE
Warnings should be written to stderr

### ISSUE THREAD

**Issue by aspettl** [fabmation-gmbh/helm-whatup#38]
Currently, warnings are written to stdout. This is not a good idea because the output (which can be configured to be yaml or json) is then invalid.

**Current behavior**, example:
```
$ helm whatup --all-namespaces -o json --ignore-deprecation 2>/dev/null
WARNING: Charts marked as deprecated will not be shown in the results.


{"releases":[],"repo_duplicates":[]}
```

This makes workarounds like https://github.com/aspettl/docker-helm-outdated/blob/f8a3d10ae32fdd7790867fcf1c293c27ab9cb97b/run.sh#L53 necessary.

**Expected behavior:**
Warnings and errors should be written to stderr.

**Comment by l0nax** [comment]
I've released [v0.5.1](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.5.1), which will print the warnings to `/dev/stderr`.
