### ISSUE TITLE
Info about latest Helm chart is deprecated

### ISSUE THREAD

**Issue by mogensen** [fabmation-gmbh/helm-whatup#39]
When running `helm whatup` we can get a `warning` in stderr if `helm-whatup` identifies that the latest version of a used helm chart is marhed as deprecated.
I would love to have this info available in the json output.

Warning when running with `-ignore-deprecation=true`  
![image](https://user-images.githubusercontent.com/592710/123393166-1fccda00-d59e-11eb-981e-628866287af8.png)

Release info when running with `-ignore-deprecation=false`. The warning is no longer printed to stderr, and the info is not available in the json.
![image](https://user-images.githubusercontent.com/592710/123393409-5c003a80-d59e-11eb-820f-de04b8b18db9.png)

I will be able to use this info as a hint that the chart I use are no longer maintained and that I should look for a chart in another Chart Repo. Or consider maintaining it myself.

**Comment by l0nax** [comment]
@mogensen I'm sorry for my late response. The latest release ([v0.6.1](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.6.1)) fixed that issue.

If your problem persists with the new version, feel free to re-open this issue.
